// Date: 10/12/2015 22:10:55
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelLightningRod extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer SecondLayer;
    ModelRenderer ThirdLayer;
    ModelRenderer Shape1;
  
  public ModelLightningRod()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(-4F, 20F, -4F, 8, 4, 8);
      Base.setRotationPoint(0F, 0F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      SecondLayer = new ModelRenderer(this, -1, 12);
      SecondLayer.addBox(-3F, 16F, -3F, 6, 4, 6);
      SecondLayer.setRotationPoint(0F, 0F, 0F);
      SecondLayer.setTextureSize(64, 32);
      SecondLayer.mirror = true;
      setRotation(SecondLayer, 0F, 0F, 0F);
      ThirdLayer = new ModelRenderer(this, 0, 22);
      ThirdLayer.addBox(-2F, 12F, -2F, 4, 4, 4);
      ThirdLayer.setRotationPoint(0F, 0F, 0F);
      ThirdLayer.setTextureSize(64, 32);
      ThirdLayer.mirror = true;
      setRotation(ThirdLayer, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 23, 12);
      Shape1.addBox(-1F, 8F, -1F, 2, 4, 2);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Base.render(f5);
    SecondLayer.render(f5);
    ThirdLayer.render(f5);
    Shape1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
